### ISSUE TITLE
チェックイン後に「渡すもの」をチケット別に整理する

### ISSUE THREAD

**Issue by fumikito** [wct2019/wp-checkin#12]
チェックインすると、スタッフに次のような画面が表示されます。この「渡すものリスト」をチケット種別ごとに整理してください。

![WP_Checkin_-_Tokyo_2019](https://user-images.githubusercontent.com/84587/66979906-27aa5a80-f0ea-11e9-9f29-f40f4d2b4224.png)

**Comment by miminari** [comment]
配布物リストですー。

## 共通
- パンフレット
- ストラップ
- ギグバンド
    - 一般来場者：緑
    - U20：黄色
- ナップサック

## スピーカーの場合
- Tシャツ（緑）

## スポンサーの場合
- Tシャツ（グレイ）

**Comment by fumikito** [comment]
@miminari ありがとうございます！

**Comment by fumikito** [comment]
クーポンコードで判別する
