### ISSUE TITLE
メールにQRコードを添付できるのか調べる

### ISSUE THREAD

**Issue by fumikito** [wct2019/wp-checkin#20]
IDを埋め込めれば生成できる？

**Comment by fumikito** [comment]
ショートコードとして使えそうなのは、チケットURLぐらい？

https://github.com/Automattic/camptix/blob/5bd479515ff468624e534f3330ca2ded9afd4b6d/camptix.php#L335-L342

**Comment by fumikito** [comment]
できたっぽい。

![IMG_F798A9417778-1](https://user-images.githubusercontent.com/84587/67801915-8fd74400-facd-11e9-8cb1-64d4cd49d868.jpg)

**Comment by miminari** [comment]
ありがとうございます！！！！！！

**Comment by fumikito** [comment]
メールの文例

```
こんにちは、[last_name] [first_name]さん。
[email]

明日はいよいよ WordCamp Tokyo 2019 ですね！
楽しみにしています。
当日はスマートフォンをお持ちになり、このQRコードをスタッフに見せてください。

<img src="https://2019.tokyo.wp-checkin.com/qrcode?f=[last_name]&amp;g=[first_name]&amp;e=[email]" alt="" />

※スマートフォンをお持ちでない場合はこのメールを印刷してスタッフに見せてください。
```
